{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/risksmobile/Pages/RiskManagementService_Mitigations/Mitigations_CreateRisks.page",
    "_Type": "Action.Type.Navigation"
}